name: PHP Composer

on:
  push:
    branches:
      - develop
      - feature
      - release
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
